version: '3.1'
services:
  postgres:
    hostname: postgres
    image: arti.dev.cray.com/third-party-docker-stable-local/postgres:11-alpine
    environment:
      - POSTGRES_USER=slsuser
      - POSTGRES_DB=sls
      - POSTGRES_HOST_AUTH_METHOD=trust
  sls-init:
    build: .
    command: ["sls-init"]
    environment:
      - POSTGRES_HOST=postgres
      - DBOPTS=sslmode=disable
      - DBUSER=slsuser
    depends_on:
      - postgres