version: '3.7'

networks:
  sls:

services:
  ct-tests-smoke:
    build:
      context: test/ct/
      dockerfile: Dockerfile
    depends_on:
      - cray-sls
    entrypoint: entrypoint.sh smoke -f smoke.json -u http://cray-sls:8376
    networks:
      - sls
#  s3:
#    #image: arti.dev.cray.com/third-party-docker-stable-local/minio/minio:RELEASE.2020-04-10T03-34-42Z
#    image: artifactory.algol60.net/docker.io-cache/minio/minio:latest
#    hostname: s3
#    environment:
#      MINIO_ACCESS_KEY: s3-access-key
#      MINIO_SECRET_KEY: s3-secret-key
#    command:  server /data
#    ports:
#      - "9000:9000"
#    networks:
#      - sls
#  s3-init:
#    image: artifactory.algol60.net/csm-docker/stable/minio/mc:latest
#    hostname: s3-init
#    environment:
#      - MC_HOST_S3=http://s3-access-key:s3-secret-key@s3:9000
#    command:  mb S3/sls
#    depends_on:
#      - s3
#    networks:
#      - sls
  postgres:
    hostname: postgres
    image: artifactory.algol60.net/docker.io/library/postgres:11-alpine
    environment:
      - POSTGRES_USER=slsuser
      - POSTGRES_DB=sls
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - sls
  sls-init:
    build: .
    command: ["sls-init"]
    environment:
      - POSTGRES_HOST=postgres
      - DBOPTS=sslmode=disable
      - DBUSER=slsuser
    depends_on:
      - postgres
    networks:
      - sls
  vault:
    hostname: vault
    image: artifactory.algol60.net/docker.io/library/vault:1.5.5
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=hms
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - sls
  cray-sls:
    build: .
    environment:
      - POSTGRES_HOST=postgres
      - DBOPTS=sslmode=disable
      - DBUSER=slsuser
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
    ports:
      - "8376:8376"
    depends_on:
#      - s3-init
      - postgres
      - sls-init
      - vault
    networks:
      - sls
