version: '3.1'
services:
  postgres:
    hostname: postgres
    image: ${REGISTRY_HOST:-artifactory.algol60.net/docker.io/library}/postgres:11-alpine
    environment:
      - POSTGRES_USER=slsuser
      - POSTGRES_DB=sls
      - POSTGRES_HOST_AUTH_METHOD=trust
  sls-init:
    image: ${REGISTRY_HOST:-artifactory.algol60.net/docker.io/library}/sls:2.1.0
    command: ["sls-init"]
    environment:
      - POSTGRES_HOST=postgres
      - DBOPTS=sslmode=disable
      - DBUSER=slsuser
      - REGISTRY_HOST=${REGISTRY_HOST:-artifactory.algol60.net/docker.io/library}
    depends_on:
      - postgres
