version: '3.1'
services:
  s3:
    image: ${REGISTRY_HOST:-artifactory.algol60.net/docker.io/minio/}minio:RELEASE.2023-04-28T18-11-17Z
    hostname: s3
    environment:
      MINIO_ACCESS_KEY: s3-access-key
      MINIO_SECRET_KEY: s3-secret-key
    command:  server /data
    ports:
      - "9000:9000"
  s3-init:
    image: ${REGISTRY_HOST:-artifactory.algol60.net/docker.io/minio/}minio:RELEASE.2023-04-28T18-11-17Z
    hostname: s3-init
    environment:
      - MC_HOST_S3=http://s3-access-key:s3-secret-key@s3:9000
    command:  mb S3/sls
    depends_on:
      - s3
  postgres:
    hostname: postgres
    image: ${REGISTRY_HOST:-artifactory.algol60.net/docker.io/library}/postgres:11-alpine
    environment:
      - POSTGRES_USER=slsuser
      - POSTGRES_DB=sls
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
  sls-init:
    build: .
    command: ["sls-init"]
    environment:
      - POSTGRES_HOST=postgres
      - DBOPTS=sslmode=disable
      - DBUSER=slsuser
    depends_on:
      - postgres
  sls:
    build: .
    environment:
      - POSTGRES_HOST=postgres
      - DBOPTS=sslmode=disable
      - DBUSER=slsuser
    ports:
      - "8376:8376"
    depends_on:
      - postgres
      - sls-init
