{
  "Hardware": {
    "x3000": {
      "Parent":     "s0",
      "Xname":      "x3000",
      "Type":       "comptype_cabinet",
      "Class":      "River",
      "TypeString": "Cabinet",
      "ExtraProperties": {
        "Networks": {
          "cn": {
            "HMN": {
              "CIDR":    "10.254.0.0/22",
              "Gateway": "10.254.0.1",
              "VLan":    4
            },
            "NMN": {
              "CIDR":    "10.252.0.0/22",
              "Gateway": "10.252.0.1",
              "VLan":    2
            }
          },
          "ncn": {
            "HMN": {
              "CIDR":    "10.254.0.0/22",
              "Gateway": "10.254.0.1",
              "VLan":    4
            },
            "NMN": {
              "CIDR":    "10.252.0.0/22",
              "Gateway": "10.252.0.1",
              "VLan":    2
            }
          }
        }
      }
    },
    "x3000c0b19n0": {
      "Parent":     "x3000c0b19",
      "Xname":      "x3000c0b19n0",
      "Type":       "comptype_chassis_bmc",
      "Class":      "River",
      "TypeString": "ChassisBMC"
    },
    "x3000c0s11b0n0": {
      "Parent":     "x3000c0s11b0",
      "Xname":      "x3000c0s11b0n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "NID":     100006,
        "Role":    "Management",
        "SubRole": "Worker",
        "Aliases": [
          "ncn-w003"
        ]
      }
    },
    "x3000c0s13b0n0": {
      "Parent":     "x3000c0s13b0",
      "Xname":      "x3000c0s13b0n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "NID":     100007,
        "Role":    "Management",
        "SubRole": "Storage",
        "Aliases": [
          "ncn-s001"
        ]
      }
    },
    "x3000c0s15b0n0": {
      "Parent":     "x3000c0s15b0",
      "Xname":      "x3000c0s15b0n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "NID":     100008,
        "Role":    "Management",
        "SubRole": "Storage",
        "Aliases": [
          "ncn-s002"
        ]
      }
    },
    "x3000c0s17b0n0": {
      "Parent":     "x3000c0s17b0",
      "Xname":      "x3000c0s17b0n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "NID":     100009,
        "Role":    "Management",
        "SubRole": "Storage",
        "Aliases": [
          "ncn-s003"
        ]
      }
    },
    "x3000c0s19b1n0": {
      "Parent":     "x3000c0s19b1",
      "Xname":      "x3000c0s19b1n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "NID":  1,
        "Role": "Compute",
        "Aliases": [
          "nid000001"
        ]
      }
    },
    "x3000c0s19b2n0": {
      "Parent":     "x3000c0s19b2",
      "Xname":      "x3000c0s19b2n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "NID":  2,
        "Role": "Compute",
        "Aliases": [
          "nid000002"
        ]
      }
    },
    "x3000c0s19b3n0": {
      "Parent":     "x3000c0s19b3",
      "Xname":      "x3000c0s19b3n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "NID":  3,
        "Role": "Compute",
        "Aliases": [
          "nid000003"
        ]
      }
    },
    "x3000c0s19b4n0": {
      "Parent":     "x3000c0s19b4",
      "Xname":      "x3000c0s19b4n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "NID":  4,
        "Role": "Compute",
        "Aliases": [
          "nid000004"
        ]
      }
    },
    "x3000c0s1b0n0": {
      "Parent":     "x3000c0s1b0",
      "Xname":      "x3000c0s1b0n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "NID":     100001,
        "Role":    "Management",
        "SubRole": "Master",
        "Aliases": [
          "ncn-m001"
        ]
      }
    },
    "x3000c0s22b0n0": {
      "Parent":     "x3000c0s22b0",
      "Xname":      "x3000c0s22b0n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "Role": "Compute"
      }
    },
    "x3000c0s23b1n0": {
      "Parent":     "x3000c0s23b1",
      "Xname":      "x3000c0s23b1n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "Role": "Compute"
      }
    },
    "x3000c0s23b2n0": {
      "Parent":     "x3000c0s23b2",
      "Xname":      "x3000c0s23b2n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "Role": "Compute"
      }
    },
    "x3000c0s24b0n0": {
      "Parent":     "x3000c0s24b0",
      "Xname":      "x3000c0s24b0n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "Role": "Compute"
      }
    },
    "x3000c0s26b0n0": {
      "Parent":     "x3000c0s26b0",
      "Xname":      "x3000c0s26b0n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "Role":    "Application",
        "SubRole": "UAN"
      }
    },
    "x3000c0s29b1n0": {
      "Parent":     "x3000c0s29b1",
      "Xname":      "x3000c0s29b1n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "NID":     100011,
        "Role":    "Management",
        "SubRole": "Worker",
        "Aliases": [
          "ncn-w005"
        ]
      }
    },
    "x3000c0s29b2n0": {
      "Parent":     "x3000c0s29b2",
      "Xname":      "x3000c0s29b2n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "NID":     100010,
        "Role":    "Management",
        "SubRole": "Worker",
        "Aliases": [
          "ncn-w004"
        ]
      }
    },
    "x3000c0s30b1n0": {
      "Parent":     "x3000c0s30b1",
      "Xname":      "x3000c0s30b1n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "NID":     100013,
        "Role":    "Management",
        "SubRole": "Worker",
        "Aliases": [
          "ncn-w007"
        ]
      }
    },
    "x3000c0s30b2n0": {
      "Parent":     "x3000c0s30b2",
      "Xname":      "x3000c0s30b2n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "NID":     100012,
        "Role":    "Management",
        "SubRole": "Worker",
        "Aliases": [
          "ncn-w006"
        ]
      }
    },
    "x3000c0s3b0n0": {
      "Parent":     "x3000c0s3b0",
      "Xname":      "x3000c0s3b0n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "NID":     100002,
        "Role":    "Management",
        "SubRole": "Master",
        "Aliases": [
          "ncn-m002"
        ]
      }
    },
    "x3000c0s5b0n0": {
      "Parent":     "x3000c0s5b0",
      "Xname":      "x3000c0s5b0n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "NID":     100003,
        "Role":    "Management",
        "SubRole": "Master",
        "Aliases": [
          "ncn-m003"
        ]
      }
    },
    "x3000c0s7b0n0": {
      "Parent":     "x3000c0s7b0",
      "Xname":      "x3000c0s7b0n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "NID":     100004,
        "Role":    "Management",
        "SubRole": "Worker",
        "Aliases": [
          "ncn-w001"
        ]
      }
    },
    "x3000c0s9b0n0": {
      "Parent":     "x3000c0s9b0",
      "Xname":      "x3000c0s9b0n0",
      "Type":       "comptype_node",
      "Class":      "River",
      "TypeString": "Node",
      "ExtraProperties": {
        "NID":     100005,
        "Role":    "Management",
        "SubRole": "Worker",
        "Aliases": [
          "ncn-w002"
        ]
      }
    },
    "x3000c0w22": {
      "Parent":     "x3000",
      "Xname":      "x3000c0w22",
      "Type":       "comptype_mgmt_switch",
      "Class":      "River",
      "TypeString": "MgmtSwitch",
      "ExtraProperties": {
        "IP4addr":          "10.254.0.2",
        "Model":            "S3048T-ON",
        "SNMPAuthPassword": "vault://hms-creds/x3000c0w22",
        "SNMPAuthProtocol": "MD5",
        "SNMPPrivPassword": "vault://hms-creds/x3000c0w22",
        "SNMPPrivProtocol": "DES",
        "SNMPUsername":     "testuser"
      }
    },
    "x3000c0w22j25": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j25",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s1b0"
        ],
        "VendorName": "ethernet1/1/25"
      }
    },
    "x3000c0w22j26": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j26",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s3b0"
        ],
        "VendorName": "ethernet1/1/26"
      }
    },
    "x3000c0w22j27": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j27",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s5b0"
        ],
        "VendorName": "ethernet1/1/27"
      }
    },
    "x3000c0w22j28": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j28",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s9b0"
        ],
        "VendorName": "ethernet1/1/28"
      }
    },
    "x3000c0w22j29": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j29",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s11b0"
        ],
        "VendorName": "ethernet1/1/29"
      }
    },
    "x3000c0w22j30": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j30",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s13b0"
        ],
        "VendorName": "ethernet1/1/30"
      }
    },
    "x3000c0w22j31": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j31",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s15b0"
        ],
        "VendorName": "ethernet1/1/31"
      }
    },
    "x3000c0w22j32": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j32",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s17b0"
        ],
        "VendorName": "ethernet1/1/32"
      }
    },
    "x3000c0w22j33": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j33",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s19b1"
        ],
        "VendorName": "ethernet1/1/33"
      }
    },
    "x3000c0w22j34": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j34",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s19b2"
        ],
        "VendorName": "ethernet1/1/34"
      }
    },
    "x3000c0w22j35": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j35",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s19b3"
        ],
        "VendorName": "ethernet1/1/35"
      }
    },
    "x3000c0w22j36": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j36",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s19b4"
        ],
        "VendorName": "ethernet1/1/36"
      }
    },
    "x3000c0w22j37": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j37",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s26b0"
        ],
        "VendorName": "ethernet1/1/37"
      }
    },
    "x3000c0w22j38": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j38",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s29b2"
        ],
        "VendorName": "ethernet1/1/38"
      }
    },
    "x3000c0w22j39": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j39",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s29b1"
        ],
        "VendorName": "ethernet1/1/39"
      }
    },
    "x3000c0w22j40": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j40",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s30b2"
        ],
        "VendorName": "ethernet1/1/40"
      }
    },
    "x3000c0w22j41": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j41",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s30b1"
        ],
        "VendorName": "ethernet1/1/41"
      }
    },
    "x3000c0w22j45": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j45",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s23b1"
        ],
        "VendorName": "ethernet1/1/45"
      }
    },
    "x3000c0w22j46": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j46",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s23b2"
        ],
        "VendorName": "ethernet1/1/46"
      }
    },
    "x3000c0w22j47": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j47",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s22b0"
        ],
        "VendorName": "ethernet1/1/47"
      }
    },
    "x3000c0w22j48": {
      "Parent":     "x3000c0w22",
      "Xname":      "x3000c0w22j48",
      "Type":       "comptype_mgmt_switch_connector",
      "Class":      "River",
      "TypeString": "MgmtSwitchConnector",
      "ExtraProperties": {
        "NodeNics": [
          "x3000c0s24b0"
        ],
        "VendorName": "ethernet1/1/48"
      }
    }
  },
  "Networks": {
    "HMN": {
      "Name":     "HMN",
      "FullName": "Hardware Management Network",
      "IPRanges": [
        "10.254.0.0/17"
      ],
      "Type":     "ethernet",
      "ExtraProperties": {
        "vlan": 4,
        "vlan_range": {
          "min": 3001,
          "max": 3999
        }
      }
    },
    "HSN": {
      "Name":     "HSN",
      "FullName": "High Speed Network",
      "IPRanges": [
        "10.253.0.0/16"
      ],
      "Type":     "slingshot10",
      "ExtraProperties": {}
    },
    "Metal": {
      "Name":     "Metal",
      "FullName": "Metal Management Network",
      "IPRanges": [
        "10.1.0.0/16"
      ],
      "Type":     "ethernet",
      "ExtraProperties": {
        "vlan": 1
      }
    },
    "MetalLB_HMN": {
      "Name":     "MetalLB_HMN",
      "FullName": "MetalLB Hardware Management Network",
      "IPRanges": [
        "10.94.100.0/24"
      ],
      "Type":     "ethernet",
      "ExtraProperties": {}
    },
    "MetalLB_NMN": {
      "Name":     "MetalLB_NMN",
      "FullName": "MetalLB Node Management Network",
      "IPRanges": [
        "10.92.100.0/24"
      ],
      "Type":     "ethernet",
      "ExtraProperties": {}
    },
    "NMN": {
      "Name":     "NMN",
      "FullName": "Node Management Network",
      "IPRanges": [
        "10.252.0.0/17"
      ],
      "Type":     "ethernet",
      "ExtraProperties": {
        "vlan": 1,
        "uai_macvlan": {
          "network_cidr": "10.252.255.0/24"
        },
        "vlan_range": {
          "min": 2001,
          "max": 2999
        }
      }
    }
  }
}
